//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestaurantReviews.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DISHES_REVIEWS
    {
        public int Id { get; set; }
        public Nullable<int> RestaurantId { get; set; }
        public Nullable<int> UserId { get; set; }
        public string Name { get; set; }
        public string Quality { get; set; }
        public string Taste { get; set; }
        public string Price { get; set; }
        public string Service { get; set; }
        public string Comment { get; set; }
    
        public virtual RESTAURANT RESTAURANT { get; set; }
        public virtual USER USER { get; set; }
    }
}
